# Generated by Django 6.0.3 on 2026-04-07 15:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='addres',
            new_name='address',
        ),
        migrations.AddField(
            model_name='recordcourse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='abiturient',
            name='class_name',
            field=models.CharField(blank=True, db_column='class', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Введите класс в формате 9а, 10б, 11в', regex='^[1-4]?[0-9][а-яА-Я]?$')]),
        ),
        migrations.AlterField(
            model_name='abiturient',
            name='email',
            field=models.EmailField(max_length=255, validators=[django.core.validators.EmailValidator(message='Введите корректный email адрес')]),
        ),
        migrations.AlterField(
            model_name='abiturient',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Имя должно содержать от 2 до 50 букв', regex='^[а-яА-Яa-zA-Z]{2,50}$')]),
        ),
        migrations.AlterField(
            model_name='abiturient',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Фамилия должна содержать от 2 до 50 букв', regex='^[а-яА-Яa-zA-Z]{2,50}$')]),
        ),
        migrations.AlterField(
            model_name='abiturient',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.parent'),
        ),
        migrations.AlterField(
            model_name='abiturient',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Введите телефон в формате +7 (___) ___-__-__', regex='^[\\+]?[0-9\\s\\-\\(\\)]{10,20}$')]),
        ),
        migrations.AlterField(
            model_name='abiturient',
            name='school',
            field=models.ForeignKey(blank=True, db_column='school_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.school'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='raspisanie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальная оценка: 1'), django.core.validators.MaxValueValidator(5, message='Максимальная оценка: 5')]),
        ),
        migrations.AlterField(
            model_name='parent',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Имя должно содержать от 2 до 50 букв', regex='^[а-яА-Яa-zA-Z]{2,50}$')]),
        ),
        migrations.AlterField(
            model_name='parent',
            name='inn',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='ИНН должен содержать 10 или 12 цифр', regex='^\\d{10}$|^\\d{12}$')]),
        ),
        migrations.AlterField(
            model_name='parent',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Фамилия должна содержать от 2 до 50 букв', regex='^[а-яА-Яa-zA-Z]{2,50}$')]),
        ),
        migrations.AlterField(
            model_name='parent',
            name='pasport',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Паспорт в формате: 4501 123456 (4 цифры + 6 цифр)', regex='^\\d{4}\\s?\\d{6}$')]),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Введите телефон в формате +7 (___) ___-__-__', regex='^[\\+]?[0-9\\s\\-\\(\\)]{10,20}$')]),
        ),
        migrations.AlterField(
            model_name='recordcourse',
            name='status',
            field=models.CharField(choices=[('В обработке', 'В обработке'), ('Подтверждена', 'Подтверждена'), ('Отклонена', 'Отклонена'), ('Завершена', 'Завершена')], default='В обработке', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=255, validators=[django.core.validators.EmailValidator(message='Введите корректный email адрес')]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Имя должно содержать от 2 до 50 букв', regex='^[а-яА-Яa-zA-Z]{2,50}$')]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Фамилия должна содержать от 2 до 50 букв', regex='^[а-яА-Яa-zA-Z]{2,50}$')]),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('teacher', 'Преподаватель'), ('student', 'Абитуриент')], default='student', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(fields=('abiturient', 'course'), name='unique_feedback_per_course'),
        ),
        migrations.AddConstraint(
            model_name='parent',
            constraint=models.UniqueConstraint(fields=('pasport', 'inn'), name='unique_parent_document'),
        ),
        migrations.AddConstraint(
            model_name='recordcourse',
            constraint=models.UniqueConstraint(fields=('abiturient', 'course'), name='unique_enrollment_per_course'),
        ),
        migrations.AddConstraint(
            model_name='school',
            constraint=models.UniqueConstraint(fields=('name', 'address'), name='unique_school_name_address'),
        ),
    ]
