# Generated by Django 6.0.3 on 2026-04-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_addres_parent_address_recordcourse_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_students',
            field=models.PositiveIntegerField(default=15, help_text='Максимальное количество студентов на курсе'),
        ),
    ]
