# Generated by Django 6.0.3 on 2026-04-07 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_course_max_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='course',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='main.course'),
        ),
    ]
