# Generated by Django 6.0.3 on 2026-04-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_feedback_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='abiturient',
            name='photo',
            field=models.ImageField(blank=True, help_text='Фотография абитуриента (необязательно)', null=True, upload_to='students/photos/'),
        ),
        migrations.AddField(
            model_name='course',
            name='photo',
            field=models.ImageField(blank=True, help_text='Фотография курса (необязательно)', null=True, upload_to='courses/photos/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, help_text='Фотография преподавателя (необязательно)', null=True, upload_to='teachers/photos/'),
        ),
    ]
