# Generated by Django 6.0.3 on 2026-04-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_feedback_moderated_at_feedback_moderated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abiturient',
            name='is_activ',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_activ',
            field=models.BooleanField(default=True),
        ),
    ]
