# Generated by Django 6.0.3 on 2026-04-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_abiturient_is_activ_teacher_is_activ'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='🏫 О нашей школе', max_length=255, verbose_name='Заголовок страницы')),
                ('main_heading', models.CharField(default='Образовательная школа подготовки к ОГЭ и ЕГЭ', max_length=255, verbose_name='Главный заголовок')),
                ('address_title', models.CharField(default='📍 Адрес', max_length=100, verbose_name='Заголовок: Адрес')),
                ('address_content', models.TextField(default='г. Муром\nул. Московская, д. 24', verbose_name='Содержимое: Адрес')),
                ('director_title', models.CharField(default='👤 Директор', max_length=100, verbose_name='Заголовок: Директор')),
                ('director_content', models.TextField(default='Писарева\nАлеся Дмитриевна', verbose_name='Содержимое: Директор')),
                ('teachers_title', models.CharField(default='👨\u200d🏫 Преподаватели', max_length=100, verbose_name='Заголовок: Преподаватели')),
                ('teachers_content', models.TextField(default='Большой штат\nквалифицированных специалистов', verbose_name='Содержимое: Преподаватели')),
                ('about_heading', models.CharField(default='📚 О нашей деятельности', max_length=255, verbose_name='Заголовок: О деятельности')),
                ('about_paragraph1', models.TextField(default='Наша образовательная школа специализируется на подготовке учащихся к успешной сдаче ОГЭ и ЕГЭ...', verbose_name='Первый абзац')),
                ('about_paragraph2', models.TextField(default='Благодаря современному подходу к обучению...', verbose_name='Второй абзац')),
                ('advantages_heading', models.CharField(default='🌟 Наши преимущества', max_length=255, verbose_name='Заголовок: Преимущества')),
                ('advantages', models.JSONField(blank=True, default=list, help_text='Формат: [{"title": "🎯 Заголовок", "desc": "Описание"}]', verbose_name='Список преимуществ')),
                ('contacts_heading', models.CharField(default='📞 Контактная информация', max_length=255, verbose_name='Заголовок: Контакты')),
                ('contact_address', models.CharField(default='г. Муром, ул. Московская, д. 24', max_length=255, verbose_name='Адрес')),
                ('contact_director', models.CharField(default='Писарева Алеся Дмитриевна', max_length=255, verbose_name='Директор')),
                ('contact_phone', models.CharField(default='+7 (999) 999-99-99', max_length=50, verbose_name='Телефон')),
                ('contact_email', models.EmailField(default='director.shcol@gmail.com', max_length=254, verbose_name='Email')),
                ('contact_schedule', models.CharField(default='Пн-Пт: 9:00 - 19:00, Сб: 10:00 - 16:00', max_length=255, verbose_name='Режим работы')),
            ],
            options={
                'verbose_name': 'Страница "О нас"',
                'verbose_name_plural': 'Страница "О нас"',
                'db_table': 'about_page',
            },
        ),
    ]
