# Generated by Django 6.0.3 on 2026-04-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_aboutpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='director',
        ),
        migrations.AddField(
            model_name='school',
            name='director_first_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Имя директора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='director_last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Фамилия директора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='director_middle_name',
            field=models.CharField(default='', max_length=100, verbose_name='Отчество директора'),
            preserve_default=False,
        ),
    ]
